kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: jenkins-role
    namespace: jenkins
rules:
- apiGroups: ["","apps"]
  resources: ["pods","deployment","svc","replicasets","statefulsets"]
  verbs: ["get","watch","describe","logs","view","patch"]