apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend-deployment
  namespace: three-tier
  labels:
    name:  backend
spec:
  replicas: 3
  
  selector:
    matchLabels:
      name : backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  template:
    metadata:
      labels:
        name:  backend
    spec:
      containers:
      - image: rajkumardockerhub/backend-test-app:v1
        name:  backend-app-image
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort:  3500
          name:  backend-port

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits: 
             cpu: "300m"
             memory: "512Mi"

        livenessProbe:
          httpGet:
            path: /healthz
            port: 3500
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /ready
            port: 3500
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3

        env:
        - name:  MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name : mongo-secret
              key : username 

        - name:  MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name : mongo-secret
              key : password 
        
        - name:  MONGO_URI
          key : mongodb://$(MONGO_USERNAME):$(MONGO_PASSWORD)@mongodb-service:27017/todo?authSource=admin

        

