---
- name: Configure DevOps EC2 Server
  hosts: devops_servers
  become: true

  roles:
    - base
    - docker
    - awscli
    - terraform
    - kubectl
    - eksctl
    - helm
    - terminal-tools