kind: Service
apiVersion: v1
metadata:
  name:  frontend-service
spec:
  selector:
    app:  frontend
  type:  ClusterIP
  ports:
  - name: http-frontend
    port:  3000
    targetPort: 3000
    protocol: TCP